### PR TITLE
Dumb commands

### PR DESCRIPTION
**Pull request by DhanrajHira**
#8 and #10 

Merge after #76

### CODE REVIEW

**Comment by Sooraj-beep** [comment]
I tried testing this PR in dev but was unable to get the bot to post in the starboard channel (main works as expected).  Please advise.

**Comment by DhanrajHira** [comment]
That's because this PR is all messed up and includes things from the old PR. This is the deadlock issue I talked about in the discord thread. Will fix tomorrow.

**Comment by DhanrajHira** [comment]
The diff from the format made me miss the actual changes that should not be in the PR.

**Review by Sooraj-beep — APPROVED** [review]
LGTM

**Pull request closed without merging**
