### PR TITLE
Full course description feature

### PR DESCRIPTION
**Pull request by nathandrapeza**

### CODE REVIEW

**Comment by aarctan** [comment]
We should avoid making http requests like this, it will be slow and can be spammed. can you extend ualberta.ca.json to include descriptions?

**Comment by Sooraj-beep** [comment]
Bet you could write a script for it

**Comment by nathandrapeza** [comment]
Thanks for the feedback, will fix soon :-)

**Comment by nathandrapeza** [comment]
Some issues with unicode - looking into it

**Comment by nathandrapeza** [comment]
> Some issues with unicode - looking into it

Looks like the ualberta.ca.json has unicode escape sequences for French accented characters (as far as I can tell), but when they're loaded in by python they work fine

**Comment by Sooraj-beep** [comment]
LGTM. Can't test on my end so if someone else also wants to review feel free to do so.

**Pull request merged**
